-- MySQL Script generated by MySQL Workbench
-- Tue Feb 24 15:26:57 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema rtp
-- -----------------------------------------------------


-- -----------------------------------------------------
-- Schema rtp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rtp` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `rtp` ;

-- -----------------------------------------------------
-- Table `rtp`.`userInfo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rtp`.`userInfo` ;

CREATE TABLE IF NOT EXISTS `rtp`.`userInfo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_fname` VARCHAR(45) NOT NULL,
  `user_lname` VARCHAR(45) NOT NULL,
  `user_email` VARCHAR(45) NOT NULL,
  `user_phone` VARCHAR(45) NULL DEFAULT NULL,
  `user_salt` VARCHAR(200) NOT NULL,
  `user_hashpass` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

INSERT INTO `rtp`.`userInfo` VALUES(DEFAULT, 'admin', 'admin', 'admin@admin.com', '', 'admin', 'f6fdffe48c908deb0f4c3bd36c032e72');
INSERT INTO `rtp`.`userInfo` VALUES(DEFAULT, 'user', 'user', 'user@user.com', '', 'user', '5cc32e366c87c4cb49e4309b75f57d64');


-- -----------------------------------------------------
-- Table `rtp`.`userLog`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rtp`.`userLog` ;

CREATE TABLE IF NOT EXISTS `rtp`.`userLog` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `log_userid` INT NOT NULL,
  `log_ip` VARCHAR(45) NOT NULL,
  `log_timestamp` TIMESTAMP NOT NULL,
  `log_activity` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `log_userid`),
  INDEX `fk_userLog_userInfo1_idx` (`log_userid` ASC),
  CONSTRAINT `fk_userLog_userInfo1`
    FOREIGN KEY (`log_userid`)
    REFERENCES `rtp`.`userInfo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rtp`.`tripPlan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rtp`.`tripPlan` ;

CREATE TABLE IF NOT EXISTS `rtp`.`tripPlan` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `trip_userid` INT NOT NULL,
  `trip_title` VARCHAR(50) NOT NULL,
  `trip_startaddress` VARCHAR(100) NOT NULL,
  `trip_endaddress` VARCHAR(100) NOT NULL,
  `trip_last_updated` TIMESTAMP NOT NULL,
  `detail_waypoint1_address` VARCHAR(100) NULL DEFAULT NULL,
  `detail_waypoint2_address` VARCHAR(100) NULL DEFAULT NULL,
  `detail_waypoint3_address` VARCHAR(100) NULL DEFAULT NULL,
  `detail_waypoint4_address` VARCHAR(100) NULL DEFAULT NULL,
  `detail_waypoint5_address` VARCHAR(100) NULL DEFAULT NULL,
  `detail_waypoint6_address` VARCHAR(100) NULL DEFAULT NULL,
  `detail_waypoint7_address` VARCHAR(100) NULL DEFAULT NULL,
  `detail_waypoint8_address` VARCHAR(100) NULL DEFAULT NULL,
  `trip_rate_avg` FLOAT NOT NULL DEFAULT 0,
  `trip_rate_num` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`, `trip_userid`),
  INDEX `fk_tripPlan_userInfo1_idx` (`trip_userid` ASC),
  CONSTRAINT `fk_tripPlan_userInfo1`
    FOREIGN KEY (`trip_userid`)
    REFERENCES `rtp`.`userInfo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rtp`.`question`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rtp`.`question` ;

CREATE TABLE IF NOT EXISTS `rtp`.`question` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `question_userid` INT NOT NULL,
  `question_text` VARCHAR(1024) NOT NULL,
  `question_timestamp` TIMESTAMP NOT NULL,
  `question_rate_avg` FLOAT NOT NULL DEFAULT 0,
  `question_rate_num` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`, `question_userid`),
  INDEX `fk_question_userInfo1_idx` (`question_userid` ASC),
  CONSTRAINT `fk_question_userInfo1`
    FOREIGN KEY (`question_userid`)
    REFERENCES `rtp`.`userInfo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `rtp`.`answer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rtp`.`answer` ;

CREATE TABLE IF NOT EXISTS `rtp`.`answer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `answer_userid` INT NOT NULL,
  `answer_questionid` INT NOT NULL,
  `answer_text` VARCHAR(512) NOT NULL,
  `answer_timestamp` TIMESTAMP NOT NULL,
  `answer_rate_avg` FLOAT NOT NULL DEFAULT 0,
  `answer_rate_num` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`, `answer_userid`, `answer_questionid`),
  INDEX `fk_answer_userInfo1_idx` (`answer_userid` ASC),
  INDEX `fk_answer_question1_idx` (`answer_questionid` ASC),
  CONSTRAINT `fk_answer_userInfo1`
    FOREIGN KEY (`answer_userid`)
    REFERENCES `rtp`.`userInfo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_answer_question1`
    FOREIGN KEY (`answer_questionid`)
    REFERENCES `rtp`.`question` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rtp`.`travelJournal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rtp`.`travelJournal` ;

CREATE TABLE IF NOT EXISTS `rtp`.`travelJournal` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `journal_userid` INT NOT NULL,
  `journal_title` VARCHAR(100) NOT NULL,
  `journal_content` TEXT NOT NULL,
  `journal_timestamp` TIMESTAMP NOT NULL,
  `journal_cover_page` VARCHAR(100),
  `journal_status` Boolean NOT NULL,
  `journal_rate_avg` FLOAT NOT NULL DEFAULT 0,
  `journal_rate_num` INT NOT NULL DEFAULT 0,
  `journal_tag1` VARCHAR(45) NULL DEFAULT NULL,
  `journal_tag2` VARCHAR(45) NULL DEFAULT NULL,
  `journal_tag3` VARCHAR(45) NULL DEFAULT NULL,
  `journal_tag4` VARCHAR(45) NULL DEFAULT NULL,
  `journal_tag5` VARCHAR(45) NULL DEFAULT NULL,

  PRIMARY KEY (`id`, `journal_userid`),
  INDEX `fk_travelJournal_userInfo1_idx` (`journal_userid` ASC),
  CONSTRAINT `fk_travelJournal_userInfo1`
    FOREIGN KEY (`journal_userid`)
    REFERENCES `rtp`.`userInfo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rtp`.`travelJournalComment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rtp`.`travelJournalComment` ;

CREATE TABLE IF NOT EXISTS `rtp`.`travelJournalComment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `comment_userid` INT NOT NULL,
  `comment_traveljournalid` INT NOT NULL,
  `comment_text` VARCHAR(512) NOT NULL,
  `comment_timestamp` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`, `comment_userid`, `comment_traveljournalid`),
  INDEX `fk_travelJournalComment_userInfo1_idx` (`comment_userid` ASC),
  INDEX `fk_travelJournalComment_travelJournal1_idx` (`comment_traveljournalid` ASC),
  CONSTRAINT `fk_travelJournalComment_userInfo1`
    FOREIGN KEY (`comment_userid`)
    REFERENCES `rtp`.`userInfo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_travelJournalComment_travelJournal1`
    FOREIGN KEY (`comment_traveljournalid`)
    REFERENCES `rtp`.`travelJournal` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `rtp`.`rating`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rtp`.`rating` ;

CREATE TABLE IF NOT EXISTS `rtp`.`rating` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rating_user_id` INT NOT NULL,
  `rating_category` INT NOT NULL,
  `rating_category_id` INT NOT NULL,
  `rating_value` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
